### ISSUE TITLE
Consider adding a LICENSE file

### ISSUE THREAD

**Issue by bfontaine** [davep/eg#4]
It’d be great to have a LICENSE/LICENCE file to know under which license this project is released.

**Comment by davep** [comment]
Is there some convention for the form of such a file, or is it just a text document that contains the licence text? For example, would linking LICENCE to [COPYING](https://github.com/davep/eg/blob/master/COPYING) be sufficient?

**Comment by bfontaine** [comment]
Ah sorry, I didn’t read `COPYING` :disappointed:

**Comment by davep** [comment]
No worries. Always good to check. :)
